dev:
  kafka_broker:
    consumer_config: {"bootstrap.servers": "bigdata1:9092,bigdata2:9092,bigdata3:9092",
             "group.id": "dev_parser_efx_kafka",
             "auto.offset.reset": "earliest",
             "enable.auto.commit": False}
    consumer_topic: ["dev_streaming_socket_efx_deals"]
    poll_timeout: 1.0
    session.timeout.ms: 6000
    dummy_server: "dev_kafka"
    producer_config: {"bootstrap.servers": "bigdata1:9092,bigdata2:9092,bigdata3:9092",
                      "client.id": "dev_parser_efx_kafka",
                      "message.max.bytes": "4194304",
                      "acks": "all"}
    producer_topic_errors: dev_streaming_kafka_efx_errors
  mssql:
    driver: ODBC Driver 17 for SQL Server
    server: bigdatasql1
    database: dev_gmta
    username: dev_python_tech_loader
    autocommit: False

  influxdb:
    host: bigdata4
    port: 8086
    database: dev_gmta_kafka
    username: dev_python_tech_loader
    reconnect_timeout_sec: 10
    reconnect_retries: 3

  directories:
    messages_dir: c:/gmta/parser_efx/messages_dir
    messages_dir_other: c:/gmta/parser_efx/messages_dir_other
    messages_dir_linux: /data/parser_efx/messages_dir
    messages_dir_linux_other: /data/parser_efx/messages_dir_other

  logger_stream:
    log_dir: log
    log_file: parser_efx_stream.log

  logger_batch:
    log_dir: log
    log_file: parser_efx_batch.log

  email:
    smtp_host: psmtp.sberbank-cib.ru
    smtp_port: 25
    smtp_email_from: dev_parser_efx_kafka@bigdata2.msk.trd.ru
    smtp_email_to: [egor_silchenko@sberbank-cib.ru, vladimir_kostyrya@sberbank-cib.ru, dmitry_larionov@sberbank-cib.ru]

sit:
  kafka_broker:
    consumer_config: {"bootstrap.servers": "bigdata1:9092,bigdata2:9092,bigdata3:9092",
             "group.id": "sit_parser_efx_kafka",
             "auto.offset.reset": "earliest",
             "enable.auto.commit": False}
    consumer_topic: ["sit_streaming_socket_efx_deals"]
    poll_timeout: 1.0
    session.timeout.ms: 6000
    dummy_server: "sit_kafka"
    producer_config: {"bootstrap.servers": "bigdata1:9092,bigdata2:9092,bigdata3:9092",
                      "client.id": "sit_parser_efx_kafka",
                      "message.max.bytes": "4194304",
                      "acks": "all"}
    producer_topic_errors: sit_streaming_kafka_efx_errors
  mssql:
    driver: ODBC Driver 17 for SQL Server
    server: bigdatasql1
    database: sit_gmta
    username: sit_python_tech_loader
    autocommit: False

  influxdb:
    host: bigdata4
    port: 8086
    database: sit_gmta_kafka
    username: sit_python_tech_loader
    reconnect_timeout_sec: 10
    reconnect_retries: 3

  directories:
    messages_dir: c:/gmta/parser_efx/messages_dir
    messages_dir_other: c:/gmta/parser_efx/messages_dir_other
    messages_dir_linux: /data/sit_parser_efx/messages_dir
    messages_dir_linux_other: /data/sit_parser_efx/messages_dir_other

  logger_stream:
    log_dir: log
    log_file: parser_efx_stream.log

  logger_batch:
    log_dir: log
    log_file: parser_efx_batch.log

  email:
    smtp_host: psmtp.sberbank-cib.ru
    smtp_port: 25
    smtp_email_from: sit_parser_efx_kafka@bigdata2.msk.trd.ru
    smtp_email_to: [egor_silchenko@sberbank-cib.ru, vladimir_kostyrya@sberbank-cib.ru, dmitry_larionov@sberbank-cib.ru]

prd:
  kafka_broker:
    consumer_config: {"bootstrap.servers": "diti1:9092,diti2:9092,diti3:9092",
             "group.id": "prd_parser_efx_kafka",
             "auto.offset.reset": "earliest",
             "enable.auto.commit": False}
    consumer_topic: ["prd_streaming_socket_efx_deals"]
    poll_timeout: 1.0
    session.timeout.ms: 6000
    dummy_server: "prd_kafka"
    producer_config: {"bootstrap.servers": "diti1:9092,diti2:9092,diti3:9092",
                      "client.id": "prd_parser_efx_kafka",
                      "message.max.bytes": "4194304",
                      "acks": "all"}
    producer_topic_errors: prd_streaming_kafka_efx_errors
  mssql:
    driver: ODBC Driver 17 for SQL Server
    server: v-gmta-16x-c001
    database: prd_gmta
    username: prd_python_tech_loader
    autocommit: False

  influxdb:
    host: diti3
    port: 8086
    database: prd_gmta_kafka
    username: prd_python_tech_loader
    reconnect_timeout_sec: 10
    reconnect_retries: 3

  directories:
    messages_dir: /data/parser_efx/messages_dir
    messages_dir_other: /data/parser_efx/messages_dir_other

  logger_stream:
    log_dir: log
    log_file: parser_efx_stream.log

  logger_batch:
    log_dir: log
    log_file: parser_efx_batch.log

  email:
    smtp_host: psmtp.sberbank-cib.ru
    smtp_port: 25
    smtp_email_from: prd_parser_efx_kafka@diti2.msk.trd.ru
    smtp_email_to: [egor_silchenko@sberbank-cib.ru, vladimir_kostyrya@sberbank-cib.ru, dmitry_larionov@sberbank-cib.ru]